name: C

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: monetdb/dev-builds:default

    steps:
    - uses: actions/checkout@v3

    - name: Install cmake
      run: |
        apt-get update 
        apt-get install -y cmake bison libpcre3-dev libssl-dev curl python3 
        rm -rf /var/lib/apt/lists/*

    - name: Build
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build .
        cmake --build . --target test
        rm -rf /tmp/*csv
        rm -rf C/dbx
