name: C

on:
    push:
        branches:
            - '*'
     # this is run every monday at 12:00
    schedule:
        - cron: '0 12 * * 1' 

jobs:
  build:

    runs-on: ubuntu-latest
    container: monetdb/dev-builds:default

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build .
        cmake --build . --target test
        rm -rf /tmp/*csv
        rm -rf C/dbx
