name: Python


on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: monetdb/dev-builds:Oct2020

    steps:
    - uses: actions/checkout@v2

    - name: Install MonetDBe
      run: pip install monetdbe

    - name: Build
      run: |

    - name: Run all files
      run: |
         cd python
         for f in *.py; do python3 "$f"; done
