name: Python


on:
    push:
        branches:
            - '*'
     # this is run every monday at 12:00
    schedule:
        - cron: '0 12 * * 1' 

jobs:
  build:

    runs-on: ubuntu-latest
    container: monetdb/dev-builds:Oct2020

    steps:
    - uses: actions/checkout@v2

    - name: Install MonetDBe
      run: pip install monetdbe

    - name: Build
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build .

    # - name: Run all files
    #   run: |
    #      cd python
    #      for f in *.py; do python3 "$f"; done
